# https://github.com/pingcap/tidb/tree/v3.0.7
LIB_NAME=tidb
LIB=github.com/pingcap/$(LIB_NAME)
LIB_BRANCH=master
LIB_TAG=v3.0.7
LIB_FSPATH=$(GOPATH)/src/$(LIB)

# server
LIB_BIN_NAME=$(LIB_NAME)-server
LIB_BIN_FSPATH=$(GOPATH)/bin/$(LIB_BIN_NAME)

# tools:

# benchkv
LIB_BIN_BENCHKV_NAME=$(LIB_NAME)-benchkv
LIB_BIN_BENCHKV_FSPATH=$(GOPATH)/bin/$(LIB_BIN_BENCHKV_NAME)

# benchdb
LIB_BIN_BENCHDB_NAME=$(LIB_NAME)-benchdb
LIB_BIN_BENCHDB_FSPATH=$(GOPATH)/bin/$(LIB_BIN_BENCHDB_NAME)

# importer
LIB_BIN_IMPORTER_NAME=$(LIB_NAME)-importer
LIB_BIN_IMPORTER_FSPATH=$(GOPATH)/bin/$(LIB_BIN_IMPORTER_NAME)

GO111MODULE=on

SAMPLE_NAME=
SAMPLE_FSPATH=

CLOUD_PROJECT_ID=
CLOUD_PROJECT_URL=



