# https://https://github.com/hybridgroup/gocv

LIB_FSPATH=$(PWD)/gocv

clone:
	git clone https://https://github.com/hybridgroup/gocv.git

dep:
	# mac
	# this one does not have all the pything crap
	brew install hybridgroup/tools/opencv

build-main:
	go build main.go
run-main:
	./main

run:	
	cd $(LIB_FSPATH)