# https://github.com/Emaisty/Realtime_stream

LIB_FSPATH=$(PWD)/Realtime_stream

clone:
	git clone https://github.com/Emaisty/Realtime_stream.git

run:	
	cd $(LIB_FSPATH)/cmd/get_active_window && go mod init
	cd $(LIB_FSPATH)/cmd/get_active_window && go run .