# https://github.com/256dpi/turing

# DOES NOT WORK. Needs ROcks DB, so forget this repo.

BIN=$(PWD)/bin

print:
	@echo

dep:
	git clone https://github.com/256dpi/turing.git

build:
	cd turing/examples/counter && go build -o $(BIN)/counter





