# https://github.com/hello2mao/go-common

dep:
	git clone https://github.com/hello2mao/go-common
all-test:
	cd go-common && go test -v ./...
mermaid-test:
	cd go-common/incubator/fsm && go test -v ./...

